-- 2014年 6月22日 星期日 18时37分29秒 CST
-- Need the drop privilege on mysql.slow_log or mysql.general_log and log_output='TABLE'
CREATE TABLE IF NOT EXISTS T_INSTANCE(
    ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY COMMENT 'MySQL实例表主键ID',
    INSTTYPE ENUM('MASTER','SLAVE') DEFAULT 'MASTER' COMMENT '实例类型',
    NAME VARCHAR(30)  CHAR SET UTF8 COLLATE UTF8_GENERAL_CI NOT NULL COMMENT 'MySQL实例名',
    IP BIGINT(11) DEFAULT 0 COMMENT 'MySQL实例的IP地址',
    PORT INT DEFAULT 3306 COMMENT 'MySQL实例监听端口',
    SOCKETPORT INT DEFAULT 7000 COMMENT '远程SLOW SQL的Socket端口',
    STATE INT DEFAULT 0 COMMENT 'MySQL实例状态:0停止;1运行;2临时下线',
    USER VARCHAR(20) CHAR SET UTF8 NOT NULL COMMENT 'MySQL实例用户名',
    PASSWD VARCHAR(150) CHAR SET UTF8 NOT NULL DEFAULT '' COMMENT '加密后的MySQL用户密码'
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS T_ALERT(
    ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY COMMENT '告警通知表主键ID',
    INSTANCE BIGINT(10) NOT NULL COMMENT '告警实例ID',
    EVENT_NAME VARCHAR(40) CHAR SET UTF8 COLLATE UTF8_GENERAL_CI COMMENT '告警原因',
    EVENT_BODY VARCHAR(500) CHAR SET UTF8 COLLATE UTF8_GENERAL_CI COMMENT '告警通知正文',
    LEVEL INT DEFAULT 0 COMMENT '告警等级:0警告,1错误,2紧急',
    RECEIVER VARCHAR(20) COMMENT '接受告警邮箱',
    STATE INT COMMENT '告警发送状态'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_CONNECTION(
    ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY COMMENT '连接数表主键ID',
    INSTANCE BIGINT(10) COMMENT '连接所在实例',
    CNT INT COMMENT '连接数',
    CHECKTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '检测连接数时间'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_QUERY(
    ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY COMMENT 'SQL查询表主键ID',
    INSTANCE BIGINT(10) COMMENT '查询所在实例',
    SQLBODY VARCHAR(200) COMMENT 'SQL',
    CHECKSUM varchar(64) COMMENT 'SQL的CHECKSUM值',
    EXECTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'SQL执行的时间点'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_REPLICAT(
    ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY COMMENT 'MySQL复制表主键ID',
    INSTANCE BIGINT(10) COMMENT 'MySQL实例',
    INSTTYPE ENUM('MASTER','SLAVE') DEFAULT 'MASTER',
    SQLTHREAD ENUM('Yes','No') DEFAULT 'Yes',
    IOTHREAD ENUM('Yes','No') DEFAULT 'Yes',
    BEHIND INT(5) DEFAULT 0 COMMENT '滞后Master秒数',
    CHECKTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '当前检测时间'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_QPS(
    ID BIGINT(11) AUTO_INCREMENT PRIMARY KEY COMMENT 'QPS表主键ID',
    INSTID BIGINT(11) DEFAULT 0 COMMENT '实例ID',
    UPTIME BIGINT(11) DEFAULT 0 COMMENT '累计运行时间',
    QUESTIONS BIGINT(11) DEFAULT 0 COMMENT '累计SQL查询',
    DIFFUPTIME INT DEFAULT 30 COMMENT '本次统计QPS间隔',
    DIFFQUESTIONS INT DEFAULT 0 COMMENT '间隔期内SQL执行次数'
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS T_SLOW (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    INSTID INT DEFAULT 0 COMMENT '实例ID',
    LOCKTIME VARCHAR(10) DEFAULT '00:00:00' COMMENT 'SQL执行锁定时长',
    QUERYTIME VARCHAR(10) DEFAULT '00:00:00' COMMENT 'SQL查询用时',
    ROWS_EXAMINED BIGINT DEFAULT 0 COMMENT 'SQL扫描的记录数',
    ROWS_SENT BIGINT DEFAULT 0 COMMENT 'SQL产生的结果集',
    SQL_TEXT VARCHAR(2000) NOT NULL COMMENT 'SQL文本',
    STARTTIME VARCHAR(20) NOT NULL COMMENT 'SQL执行时间',
    STATE TINYINT DEFAULT 0 COMMENT 'SQL状态',
    USER_HOST VARCHAR(100) COMMENT 'SQL来源用户及主机',
    ONDB varchar(20) NOT NULL COMMENT 'SQL所在DATABASE',
    OBJID VARCHAR(40) NOT NULL COMMENT 'SHA1 Hash',
    UNIQUE KEY INX_UNQ_OBJID(OBJID),
    UNIQUE KEY INX_UNQ_STTST(STARTTIME,SQL_TEXT(250))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS T_HITRATE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    INSTID INT COMMENT '实例ID',
    CHECKTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '检测时间',
    RATE DOUBLE DEFAULT 0 COMMENT 'SQL Cache命中率'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
